import React from "react";

export default function App() {
  return (
      <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white text-gray-900 font-sans">
            {/* Cabeçalho */}
                  <header className="text-center py-10 bg-blue-600 text-white shadow-lg">
                          <h1 className="text-4xl font-bold">🚀 Destrava ENEM Norte</h1>
                                  <p className="mt-2 text-lg">
                                            A plataforma que te prepara pro ENEM de forma divertida, prática e 100% online!
                                                    </p>
                                                          </header>

                                                                {/* Seção principal */}
                                                                      <main className="max-w-5xl mx-auto px-6 py-12 space-y-12">
                                                                              {/* Foto principal */}
                                                                                      <div className="rounded-2xl overflow-hidden shadow-xl">
                                                                                                <img
                                                                                                            src="https://github.com/roneyjunioroficial015-wq/destrava-enem-norte/blob/main/1762551274524.jpg?raw=true"
                                                                                                                        alt="Alunos estudando ENEM"
                                                                                                                                    className="w-full"
                                                                                                                                              />
                                                                                                                                                      </div>

                                                                                                                                                              {/* Texto de explicação */}
                                                                                                                                                                      <section className="text-center space-y-4">
                                                                                                                                                                                <h2 className="text-3xl font-bold text-blue-700">
                                                                                                                                                                                            Estude de forma inteligente e interativa
                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                <p className="text-lg text-gray-700 leading-relaxed">
                                                                                                                                                                                                                            O <strong>Destrava ENEM Norte</strong> é o novo jeito de se preparar para o ENEM.
                                                                                                                                                                                                                                        Aqui você aprende com resumos simples, simulados rápidos e desafios diários
                                                                                                                                                                                                                                                    — tudo pensado pra te deixar mais confiante na prova.
                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                        <p className="text-lg text-gray-700 leading-relaxed">
                                                                                                                                                                                                                                                                                    Criamos um ambiente prático, leve e direto ao ponto.
                                                                                                                                                                                                                                                                                                Você estuda pelo celular, no seu ritmo, com acesso rápido e suporte no WhatsApp!
                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                          {/* Galeria de imagens */}
                                                                                                                                                                                                                                                                                                                                  <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                            <img
                                                                                                                                                                                                                                                                                                                                                        src="https://github.com/roneyjunioroficial015-wq/destrava-enem-norte/blob/main/1762550910299.jpg?raw=true"
                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                alt="Estudo 1"
                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                    <img
                                                                                                                                                                                                                                                                                                                                                                                                                src="https://github.com/roneyjunioroficial015-wq/destrava-enem-norte/blob/main/1762551038530.jpg?raw=true"
                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-2xl shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                        alt="Estudo 2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src="https://github.com/roneyjunioroficial015-wq/destrava-enem-norte/blob/main/1762550943434.jpg?raw=true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt="Estudo 3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Botões de ação */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="https://pay.kiwify.com.br/SB4sYeC"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="inline-block bg-blue-600 hover:bg-blue-700 text-white text-lg font-semibold px-8 py-3 rounded-full shadow-md transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      🎓 Entrar no Curso Agora
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="https://wa.me/5592999999999" // coloque aqui seu número com DDD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="inline-block bg-green-500 hover:bg-green-600 text-white text-lg font-semibold px-8 py-3 rounded-full shadow-md transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              💬 Falar no WhatsApp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Rodapé */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <footer className="bg-blue-700 text-white text-center py-6 mt-16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    © {new Date().getFullYear()} Destrava ENEM Norte — Todos os direitos reservados.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs opacity-80 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Feito com ❤️ para ajudar estudantes do Norte do Brasil.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }